language: android
android:
  components:
    - build-tools-28.0.3
    - android-28

before_script:
  - chmod +x ./gradlew

script:
  - ./gradlew install

deploy:
  provider: script
  script: ./gradlew assemble bintrayUpload
  skip_cleanup: true
  file: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  on:
    branch: master